spring:
  main:
    headless: false
  application:
    name: av-car-api
  datasource:
    url: jdbc:postgresql://localhost:5432/avcar
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jackson:
    date-format: yyyy-MM-dd
    time-zone: America/Sao_Paulo

server:
  port: 8080

springdoc:
  swagger-ui:
    url: http://localhost:8080/swagger-ui/index.html