@startuml
skinparam backgroundColor #FFFFFF
skinparam actorStyle awesome
skinparam useCaseBorderColor #2E86C1
skinparam useCaseBackgroundColor #EBF5FB
skinparam useCaseFontColor #1A5276
skinparam useCaseFontSize 14
skinparam actorBorderColor #2E86C1
skinparam actorBackgroundColor #AED6F1
skinparam actorFontSize 14
skinparam defaultFontSize 13
skinparam arrowColor #2E86C1
skinparam defaultTextAlignment center
skinparam padding 20

title **Mecanico**

rectangle "AV-CAR Auto Center" {
  (Cadastrar Veiculo) as UC4
  (Consultar Estoque) as UC9
  (Abrir Ordem de Servico) as UC11
  (Gerenciar Ciclo da OS) as UC12
  (Adicionar Itens a OS) as UC13
}

actor Mecanico as mec

mec --> UC4
mec --> UC9
mec --> UC11
mec --> UC12
mec --> UC13

@enduml
