/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.senai.fatesg.avcar.swing.views.telas;

import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import br.edu.senai.fatesg.avcar.business.clientes.ClienteController;
import javax.swing.JOptionPane;

/**
 *
 * @author lucio-aguiar
 */
@Component
public class CadastroVeiculo extends javax.swing.JPanel {

    @Autowired
    private ClienteController clienteController;
    
    @Autowired
    private br.edu.senai.fatesg.avcar.business.veiculos.VeiculoController veiculoController;


    /**
     * Creates new form CadastroVeiculo
     */
    public CadastroVeiculo() {
        initComponents();
    }
    
    @jakarta.annotation.PostConstruct
    public void initLogic() {
        // 1. Carrega as marcas com imagens e liga a atualização automática dos modelos!
        br.edu.senai.fatesg.avcar.swing.views.telas.utils.VeiculoFormUtil.configurarComboMarcasEModelos(
            jComboBoxMarca, jComboBoxModelo, veiculoController
        );

        // 2. Carrega todos os clientes do banco no ComboBox
        br.edu.senai.fatesg.avcar.swing.views.telas.utils.VeiculoFormUtil.configurarComboClientes(
            jComboBoxCliente, clienteController
        );
        
        // 3. Deixa Placa e Chassi chiques (tudo maiúsculo em tempo real e com limite)
        br.edu.senai.fatesg.avcar.swing.views.telas.utils.FormatadorUtil.setCaixaAlta(jTextFieldPlaca, 8); // Placas Mercosul ou Antigas = Max 8 caracteres
        br.edu.senai.fatesg.avcar.swing.views.telas.utils.FormatadorUtil.setCaixaAlta(jTextFieldChassi, 17); // Chassi = 17 caracteres
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroVeiculo = new javax.swing.JPanel();
        jLabelPlaca = new javax.swing.JLabel();
        jTextFieldPlaca = new javax.swing.JTextField();
        jTextFieldChassi = new javax.swing.JTextField();
        jLabelChassi = new javax.swing.JLabel();
        jLabelAnoFabricacao = new javax.swing.JLabel();
        jTextFieldAnoFabricacao = new javax.swing.JTextField();
        jLabelAnoModelo = new javax.swing.JLabel();
        jTextFieldAnoModelo = new javax.swing.JTextField();
        jLabelCor = new javax.swing.JLabel();
        jLabelKMAtual = new javax.swing.JLabel();
        jLabelAcessorios = new javax.swing.JLabel();
        jLabelEmailMarca = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jButtonSalvarVeiuclo = new javax.swing.JButton();
        jButtonCancelarVeiculo = new javax.swing.JButton();
        jFormattedTextFieldKMAtual = new javax.swing.JFormattedTextField();
        jLabelCliente = new javax.swing.JLabel();
        jTextFieldCor = new javax.swing.JTextField();
        jTextFieldAcessorios = new javax.swing.JTextField();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jComboBoxModelo = new javax.swing.JComboBox<>();
        jComboBoxCliente = new javax.swing.JComboBox<>();

        setToolTipText("Novo Cliente");

        jPanelCadastroVeiculo.setToolTipText("Insira os Dados do novo Cliente");

        jLabelPlaca.setText("Placa:");

        jLabelChassi.setText("Chassi:");

        jLabelAnoFabricacao.setText("Ano Fab.");

        jLabelAnoModelo.setText("Ano Mod.");

        jLabelCor.setText("Cor:");

        jLabelKMAtual.setText("KM Atual:");

        jLabelAcessorios.setText("Acessórios");

        jLabelEmailMarca.setText("Marca:");

        jLabelModelo.setText("Modelo: ");

        jButtonSalvarVeiuclo.setText("Salvar");
        jButtonSalvarVeiuclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarVeiucloActionPerformed(evt);
            }
        });

        jButtonCancelarVeiculo.setText("Cancelar");
        jButtonCancelarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarVeiculoActionPerformed(evt);
            }
        });

        jFormattedTextFieldKMAtual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabelCliente.setText("Cliente:");

        jComboBoxMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelCadastroVeiculoLayout = new javax.swing.GroupLayout(jPanelCadastroVeiculo);
        jPanelCadastroVeiculo.setLayout(jPanelCadastroVeiculoLayout);
        jPanelCadastroVeiculoLayout.setHorizontalGroup(
            jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroVeiculoLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroVeiculoLayout.createSequentialGroup()
                        .addComponent(jButtonSalvarVeiuclo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroVeiculoLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPlaca)
                            .addComponent(jLabelChassi)
                            .addComponent(jLabelAnoFabricacao)
                            .addComponent(jLabelAnoModelo)
                            .addComponent(jLabelCor)
                            .addComponent(jLabelKMAtual)
                            .addComponent(jLabelAcessorios)
                            .addComponent(jLabelEmailMarca)
                            .addComponent(jLabelModelo)
                            .addComponent(jLabelCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPlaca)
                            .addComponent(jTextFieldChassi)
                            .addComponent(jTextFieldAcessorios)
                            .addComponent(jComboBoxCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelCadastroVeiculoLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldKMAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldCor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                        .addComponent(jTextFieldAnoModelo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldAnoFabricacao, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jComboBoxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(40, 40, 40))
        );
        jPanelCadastroVeiculoLayout.setVerticalGroup(
            jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVeiculoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlaca)
                    .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChassi)
                    .addComponent(jTextFieldChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAnoFabricacao)
                    .addComponent(jTextFieldAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAnoModelo)
                    .addComponent(jTextFieldAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCor)
                    .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKMAtual)
                    .addComponent(jFormattedTextFieldKMAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAcessorios)
                    .addComponent(jTextFieldAcessorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailMarca)
                    .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModelo)
                    .addComponent(jComboBoxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCliente))
                .addGap(21, 21, 21)
                .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarVeiuclo)
                    .addComponent(jButtonCancelarVeiculo))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarVeiucloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarVeiucloActionPerformed
        salvarVeiculo();
    }//GEN-LAST:event_jButtonSalvarVeiucloActionPerformed

    private void jButtonCancelarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarVeiculoActionPerformed
        cancelar();
    }//GEN-LAST:event_jButtonCancelarVeiculoActionPerformed

    private Long idVeiculoEmEdicao = null;

    public void preencherParaEdicao(Long id) {
        this.idVeiculoEmEdicao = id;
        
        br.edu.senai.fatesg.avcar.business.veiculos.VeiculoDTO veiculo = veiculoController.buscarPorId(id).getBody();
        
        if (veiculo != null) {
            jTextFieldPlaca.setText(veiculo.getPlaca());
            jTextFieldChassi.setText(veiculo.getChassi());
            jTextFieldAnoFabricacao.setText(String.valueOf(veiculo.getAnoFabricacao()));
            jTextFieldAnoModelo.setText(String.valueOf(veiculo.getAnoModelo()));
            jTextFieldCor.setText(veiculo.getCor());
            jTextFieldAcessorios.setText(veiculo.getAcessorios());
            jFormattedTextFieldKMAtual.setValue(veiculo.getQuilometragem()); // Evita crash no formatter

            // Seleciona o Cliente
            for (int i = 0; i < jComboBoxCliente.getItemCount(); i++) {
                Object item = jComboBoxCliente.getItemAt(i);
                if (item instanceof br.edu.senai.fatesg.avcar.swing.views.telas.utils.VeiculoFormUtil.ClienteItem) {
                    if (((br.edu.senai.fatesg.avcar.swing.views.telas.utils.VeiculoFormUtil.ClienteItem) item).id.equals(veiculo.getClienteId())) {
                        jComboBoxCliente.setSelectedIndex(i);
                        break;
                    }
                }
            }

            // Seleciona a Marca
            for (int i = 0; i < jComboBoxMarca.getItemCount(); i++) {
                Object item = jComboBoxMarca.getItemAt(i);
                if (item instanceof br.edu.senai.fatesg.avcar.swing.views.telas.utils.VeiculoFormUtil.MarcaItem) {
                    if (((br.edu.senai.fatesg.avcar.swing.views.telas.utils.VeiculoFormUtil.MarcaItem) item).nome.equals(veiculo.getMarcaNome())) {
                        jComboBoxMarca.setSelectedIndex(i);
                        break;
                    }
                }
            }

            // Seleciona o Modelo
            for (int i = 0; i < jComboBoxModelo.getItemCount(); i++) {
                String modStr = jComboBoxModelo.getItemAt(i) != null ? jComboBoxModelo.getItemAt(i).toString() : "";
                if (modStr.contains("(" + veiculo.getModeloId() + ")")) {
                    jComboBoxModelo.setSelectedIndex(i);
                    break;
                }
            }
        }
    }

    public void prepararParaNovo() {
        this.idVeiculoEmEdicao = null;
        limparCampos();
    }

    private void salvarVeiculo() {
        try {
            int af = Integer.parseInt(jTextFieldAnoFabricacao.getText().trim());
            int am = Integer.parseInt(jTextFieldAnoModelo.getText().trim());
            int km = Integer.parseInt(jFormattedTextFieldKMAtual.getText().trim().replace(".", "").replace(",", ""));
            
            Long modeloId = null;
            if (jComboBoxModelo.getSelectedItem() != null) {
                String modStr = jComboBoxModelo.getSelectedItem().toString();
                if (modStr.contains("(")) {
                    int start = modStr.lastIndexOf('(') + 1;
                    int end = modStr.lastIndexOf(')');
                    modeloId = Long.parseLong(modStr.substring(start, end));
                }
            }
            
            Long clienteId = null;
            Object selectedCliente = jComboBoxCliente.getSelectedItem();
            if (selectedCliente != null) {
                if (selectedCliente instanceof br.edu.senai.fatesg.avcar.swing.views.telas.utils.VeiculoFormUtil.ClienteItem) {
                    clienteId = ((br.edu.senai.fatesg.avcar.swing.views.telas.utils.VeiculoFormUtil.ClienteItem) selectedCliente).id;
                }
            }

            br.edu.senai.fatesg.avcar.business.veiculos.VeiculoController.VeiculoRequest req = 
                new br.edu.senai.fatesg.avcar.business.veiculos.VeiculoController.VeiculoRequest(
                    jTextFieldPlaca.getText(), jTextFieldChassi.getText(), af, am, jTextFieldCor.getText(), 
                    km, jTextFieldAcessorios.getText(), modeloId, clienteId
            );

            if (idVeiculoEmEdicao == null) {
                veiculoController.salvar(req);
                JOptionPane.showMessageDialog(this, "Veículo cadastrado com sucesso!");
            } else {
                veiculoController.atualizar(idVeiculoEmEdicao, req);
                JOptionPane.showMessageDialog(this, "Veículo atualizado com sucesso!");
            }
            cancelar();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Anos e Quilometragem devem ser números inteiros.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage());
        }
    }

    private void limparCampos() {
        jTextFieldPlaca.setText("");
        jTextFieldChassi.setText("");
        jTextFieldAnoFabricacao.setText("");
        jTextFieldAnoModelo.setText("");
        jTextFieldCor.setText("");
        jTextFieldAcessorios.setText("");
        jFormattedTextFieldKMAtual.setValue(null);
        if (jComboBoxMarca.getItemCount() > 0) jComboBoxMarca.setSelectedIndex(0);
        if (jComboBoxCliente.getItemCount() > 0) jComboBoxCliente.setSelectedIndex(0);
    }

    private void cancelar() {
        limparCampos();
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarVeiculo;
    private javax.swing.JButton jButtonSalvarVeiuclo;
    private javax.swing.JComboBox<br.edu.senai.fatesg.avcar.swing.views.telas.utils.VeiculoFormUtil.ClienteItem> jComboBoxCliente;
    private javax.swing.JComboBox<br.edu.senai.fatesg.avcar.swing.views.telas.utils.VeiculoFormUtil.MarcaItem> jComboBoxMarca;
    private javax.swing.JComboBox<String> jComboBoxModelo;
    private javax.swing.JFormattedTextField jFormattedTextFieldKMAtual;
    private javax.swing.JLabel jLabelAcessorios;
    private javax.swing.JLabel jLabelAnoFabricacao;
    private javax.swing.JLabel jLabelAnoModelo;
    private javax.swing.JLabel jLabelChassi;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelEmailMarca;
    private javax.swing.JLabel jLabelKMAtual;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JPanel jPanelCadastroVeiculo;
    private javax.swing.JTextField jTextFieldAcessorios;
    private javax.swing.JTextField jTextFieldAnoFabricacao;
    private javax.swing.JTextField jTextFieldAnoModelo;
    private javax.swing.JTextField jTextFieldChassi;
    private javax.swing.JTextField jTextFieldCor;
    private javax.swing.JTextField jTextFieldPlaca;
    // End of variables declaration//GEN-END:variables
}
