/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.senai.fatesg.avcar.swing.views.telas;

import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import br.edu.senai.fatesg.avcar.business.clientes.ClienteController;
import javax.swing.JOptionPane;

/**
 *
 * @author lucio-aguiar
 */
@Component
public class CadastroClientePJ extends javax.swing.JPanel {

    @Autowired
    private ClienteController clienteController;

    @Autowired
    private org.springframework.context.ApplicationContext ctx;

    /**
     * Creates new form CadastroClienteGUI
     */
    public CadastroClientePJ() {
        initComponents();
    }
    
    @jakarta.annotation.PostConstruct
    public void initLogic() {
        br.edu.senai.fatesg.avcar.swing.views.telas.utils.ClienteFormUtil.configurarNavegacaoRadios(
            this, jRadioButtonPessoaFisicaPJ, jRadioButtonPessoaJuridicaPJ, ctx, false
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPJ = new javax.swing.JPanel();
        jLabelTipoPJ = new javax.swing.JLabel();
        jLabelNomePJ = new javax.swing.JLabel();
        jTextFieldNomePJ = new javax.swing.JTextField();
        jTextFieldEnderecoPJ = new javax.swing.JTextField();
        jLabelEnderecoPJ = new javax.swing.JLabel();
        jLabelBairroPJ = new javax.swing.JLabel();
        jTextFieldBairroPJ = new javax.swing.JTextField();
        jLabelCidadePJ = new javax.swing.JLabel();
        jTextFieldCidadePJ = new javax.swing.JTextField();
        jLabelEstadoPJ = new javax.swing.JLabel();
        jLabelCEPPJ = new javax.swing.JLabel();
        jLabelTelefonePJ = new javax.swing.JLabel();
        jLabelEmailPJ = new javax.swing.JLabel();
        jTextFieldEmailPJ = new javax.swing.JTextField();
        jLabelCNPJPJ = new javax.swing.JLabel();
        jButtonSalvarPJ = new javax.swing.JButton();
        jButtonCancelarPJ = new javax.swing.JButton();
        jComboBoxEstadoPJ = new javax.swing.JComboBox<>();
        jFormattedTextFieldCNPJPJ = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCEPPJ = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefonePJ = new javax.swing.JFormattedTextField();
        jRadioButtonPessoaFisicaPJ = new javax.swing.JRadioButton();
        jRadioButtonPessoaJuridicaPJ = new javax.swing.JRadioButton();
        jLabelInscricaoEstadualPJ = new javax.swing.JLabel();
        jFormattedTextFieldInscricaoEstadualPJ = new javax.swing.JFormattedTextField();

        setToolTipText("Novo Cliente");

        jPanelPJ.setToolTipText("Insira os Dados do novo Cliente");

        jLabelTipoPJ.setText("Tipo:");

        jLabelNomePJ.setText("Nome:");

        jLabelEnderecoPJ.setText("Endereço:");

        jLabelBairroPJ.setText("Bairro:");

        jLabelCidadePJ.setText("Cidade:");

        jLabelEstadoPJ.setText("Estado:");

        jLabelCEPPJ.setText("CEP:");

        jLabelTelefonePJ.setText("Telefone:");

        jLabelEmailPJ.setText("E-mail:");

        jLabelCNPJPJ.setText("CNPJ");

        jButtonSalvarPJ.setText("Salvar");
        jButtonSalvarPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarPJActionPerformed(evt);
            }
        });

        jButtonCancelarPJ.setText("Cancelar");
        jButtonCancelarPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarPJActionPerformed(evt);
            }
        });

        jComboBoxEstadoPJ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GO", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "AC", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        try {
            jFormattedTextFieldCNPJPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-## ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldCEPPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldTelefonePJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jRadioButtonPessoaFisicaPJ.setText("Pessoa Física");

        jRadioButtonPessoaJuridicaPJ.setText("Pessoa Jurídica");

        jLabelInscricaoEstadualPJ.setText("Inscrição Estadual");

        javax.swing.GroupLayout jPanelPJLayout = new javax.swing.GroupLayout(jPanelPJ);
        jPanelPJ.setLayout(jPanelPJLayout);
        jPanelPJLayout.setHorizontalGroup(
            jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPJLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPJLayout.createSequentialGroup()
                        .addComponent(jButtonSalvarPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPJLayout.createSequentialGroup()
                        .addGroup(jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTipoPJ)
                            .addComponent(jLabelNomePJ)
                            .addComponent(jLabelEnderecoPJ)
                            .addComponent(jLabelBairroPJ)
                            .addComponent(jLabelCidadePJ)
                            .addComponent(jLabelEstadoPJ)
                            .addComponent(jLabelCEPPJ)
                            .addComponent(jLabelTelefonePJ)
                            .addComponent(jLabelEmailPJ)
                            .addComponent(jLabelCNPJPJ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelPJLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jRadioButtonPessoaFisicaPJ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonPessoaJuridicaPJ))
                            .addComponent(jTextFieldNomePJ, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(jTextFieldEnderecoPJ)
                            .addComponent(jTextFieldBairroPJ)
                            .addComponent(jTextFieldCidadePJ)
                            .addComponent(jTextFieldEmailPJ)
                            .addComponent(jComboBoxEstadoPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCEPPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldTelefonePJ, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCNPJPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPJLayout.createSequentialGroup()
                        .addComponent(jLabelInscricaoEstadualPJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldInscricaoEstadualPJ)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelPJLayout.setVerticalGroup(
            jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPJLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoPJ)
                    .addComponent(jRadioButtonPessoaFisicaPJ)
                    .addComponent(jRadioButtonPessoaJuridicaPJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomePJ)
                    .addComponent(jTextFieldNomePJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnderecoPJ)
                    .addComponent(jTextFieldEnderecoPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBairroPJ)
                    .addComponent(jTextFieldBairroPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidadePJ)
                    .addComponent(jTextFieldCidadePJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstadoPJ)
                    .addComponent(jComboBoxEstadoPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCEPPJ)
                    .addComponent(jFormattedTextFieldCEPPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefonePJ)
                    .addComponent(jFormattedTextFieldTelefonePJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailPJ)
                    .addComponent(jTextFieldEmailPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCNPJPJ)
                    .addComponent(jFormattedTextFieldCNPJPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldInscricaoEstadualPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInscricaoEstadualPJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanelPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarPJ)
                    .addComponent(jButtonCancelarPJ))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarPJActionPerformed
        salvarCliente();
    }//GEN-LAST:event_jButtonSalvarPJActionPerformed

    private void jButtonCancelarPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarPJActionPerformed
        cancelar();
    }//GEN-LAST:event_jButtonCancelarPJActionPerformed

    private Long idClienteEmEdicao = null;

    public void preencherParaEdicao(Long id) {
        this.idClienteEmEdicao = id;
        
        br.edu.senai.fatesg.avcar.business.clientes.ClienteDTO cliente = clienteController.buscarPorId(id).getBody();
        
        if (cliente != null) {
            jTextFieldNomePJ.setText(cliente.getNome());
            jTextFieldEnderecoPJ.setText(cliente.getEndereco());
            jTextFieldBairroPJ.setText(cliente.getBairro());
            jTextFieldCidadePJ.setText(cliente.getCidade());
            if (cliente.getEstado() != null) jComboBoxEstadoPJ.setSelectedItem(cliente.getEstado());
            jTextFieldEmailPJ.setText(cliente.getEmail());
            jFormattedTextFieldCEPPJ.setText(cliente.getCep());
            jFormattedTextFieldTelefonePJ.setText(cliente.getTelefone());
            jFormattedTextFieldCNPJPJ.setText(cliente.getDocumento());
            if (cliente.getInscricaoEstadual() != null) {
                jFormattedTextFieldInscricaoEstadualPJ.setText(cliente.getInscricaoEstadual());
            }
            
            if ("PF".equalsIgnoreCase(cliente.getTipo())) {
                jRadioButtonPessoaFisicaPJ.setSelected(true);
            } else {
                jRadioButtonPessoaJuridicaPJ.setSelected(true);
            }
            
            // Impede a mudança de tipo de cliente durante a edição
            jRadioButtonPessoaFisicaPJ.setEnabled(false);
            jRadioButtonPessoaJuridicaPJ.setEnabled(false);
        }
    }

    public void prepararParaNovo() {
        this.idClienteEmEdicao = null;
        limparCampos();
        
        // Libera os botões de tipo ao criar novo cliente
        jRadioButtonPessoaFisicaPJ.setEnabled(true);
        jRadioButtonPessoaJuridicaPJ.setEnabled(true);
        jRadioButtonPessoaJuridicaPJ.setSelected(true);
    }

    private void salvarCliente() {
        br.edu.senai.fatesg.avcar.swing.views.telas.utils.ClienteFormUtil.salvarPessoaJuridica(
            this, 
            clienteController, 
            idClienteEmEdicao, 
            jTextFieldNomePJ.getText(), 
            jTextFieldEnderecoPJ.getText(), 
            jTextFieldBairroPJ.getText(), 
            jTextFieldCidadePJ.getText(), 
            jComboBoxEstadoPJ.getSelectedItem() != null ? jComboBoxEstadoPJ.getSelectedItem().toString() : "", 
            jFormattedTextFieldCEPPJ.getText(), 
            jFormattedTextFieldTelefonePJ.getText(), 
            jTextFieldEmailPJ.getText(), 
            jFormattedTextFieldCNPJPJ.getText(),
            jFormattedTextFieldInscricaoEstadualPJ.getText()
        );
    }

    private void limparCampos() {
        jTextFieldNomePJ.setText("");
        jTextFieldEnderecoPJ.setText("");
        jTextFieldBairroPJ.setText("");
        jTextFieldCidadePJ.setText("");
        jTextFieldEmailPJ.setText("");
        jFormattedTextFieldCEPPJ.setValue(null);
        jFormattedTextFieldTelefonePJ.setValue(null);
        jFormattedTextFieldCNPJPJ.setValue(null);
        jFormattedTextFieldInscricaoEstadualPJ.setValue(null);
    }

    private void cancelar() {
        limparCampos();
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarPJ;
    private javax.swing.JButton jButtonSalvarPJ;
    private javax.swing.JComboBox<String> jComboBoxEstadoPJ;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEPPJ;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNPJPJ;
    private javax.swing.JFormattedTextField jFormattedTextFieldInscricaoEstadualPJ;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefonePJ;
    private javax.swing.JLabel jLabelBairroPJ;
    private javax.swing.JLabel jLabelCEPPJ;
    private javax.swing.JLabel jLabelCNPJPJ;
    private javax.swing.JLabel jLabelCidadePJ;
    private javax.swing.JLabel jLabelEmailPJ;
    private javax.swing.JLabel jLabelEnderecoPJ;
    private javax.swing.JLabel jLabelEstadoPJ;
    private javax.swing.JLabel jLabelInscricaoEstadualPJ;
    private javax.swing.JLabel jLabelNomePJ;
    private javax.swing.JLabel jLabelTelefonePJ;
    private javax.swing.JLabel jLabelTipoPJ;
    private javax.swing.JPanel jPanelPJ;
    private javax.swing.JRadioButton jRadioButtonPessoaFisicaPJ;
    private javax.swing.JRadioButton jRadioButtonPessoaJuridicaPJ;
    private javax.swing.JTextField jTextFieldBairroPJ;
    private javax.swing.JTextField jTextFieldCidadePJ;
    private javax.swing.JTextField jTextFieldEmailPJ;
    private javax.swing.JTextField jTextFieldEnderecoPJ;
    private javax.swing.JTextField jTextFieldNomePJ;
    // End of variables declaration//GEN-END:variables
}
